name: Linux_MacOs-release

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
            
      - name: Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install click
      
      - name: Clone Repo
        run: git clone https://github.com/valkarias/PBuild.git

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Freeze CLI
        run: |
          cd PBuild/src
          pyinstaller --onefile --hidden-import utils.py pbuild.py
      
      - name: Zip
        run: |
          cd src/dist
          zip "PBuild_${{ matrix.os }}.zip" pbuild

      - name: Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -f -a latest -m "Latest release"
          git push origin -f --follow-tags latest
        
      - name: Release
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/valkarias/PBuild/releases/70667137/assets{?name,label}
          release_id: 70667137
          asset_path: Pbuild/src/dist/PBuild_${{ matrix.os }}.zip
          asset_name: "${{ steps.date.outputs.date }}a-${{ matrix.os }}.zip"
          asset_content_type: application/zip

  ###########

  # test & run
  test:
    needs: [ build ]
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install PBuild
        run: powershell Invoke-WebRequest -Uri "https://github.com/valkarias/PBuild/releases/download/latest/2022-06-27a-windows-latest.zip" -OutFile "PBuild.zip"
        
      - name: Unzip
        run: |
          unzip -q PBuild.zip

      - name: Run test
        run:
          PBuild\pbuild
