name: Windows-release

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  # test & run
  test:
    runs-on: windows-latest
    
    steps:
      - name: Install PBuild
        run: powershell Invoke-WebRequest -Uri "https://github.com/valkarias/Pa/releases/download/windows-latest/PBuild_windows-latest.zip" -OutFile "PBuild.zip"
        
      - name: Unzip
        run: |
          powershell Expand-Archive -Path PBuild.zip -DestinationPath PBuild

      - name: Run test
        run:
          PBuild\pbuild version
