name: Windows-release

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  # test & run
  test:
    runs-on: windows-latest
    
    steps:
      - name: WGET
        uses: wei/wget@v1.1.1

      - name: Install PBuild
        run: wget https://github.com/valkarias/Pa/archive/master.zip -O Pa.zip
        
      - name: Unzip
        run: |
          cd %homepath%
          powershell Expand-Archive -Path PBuild.zip -DestinationPath %homepath%

      - name: Run test
        run:
          cd %homepath%
          PBuild\pbuild version